<?php

use Illuminate\Database\Seeder;
use App\models\Banco;

class BancoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Banco::create(['ban_codigo' => '001', 'ban_nome' => '001 - BANCO DO BRASIL S/A']);
        Banco::create(['ban_codigo' => '002', 'ban_nome' => '002 - BANCO CENTRAL DO BRASIL']);
        Banco::create(['ban_codigo' => '003', 'ban_nome' => '003 - BANCO DA AMAZONIA S.A']);
        Banco::create(['ban_codigo' => '004', 'ban_nome' => '004 - BANCO DO NORDESTE DO BRASIL S.A']);
        Banco::create(['ban_codigo' => '007', 'ban_nome' => '007 - BANCO NAC DESENV. ECO. SOCIAL S.A']);
        Banco::create(['ban_codigo' => '008', 'ban_nome' => '008 - BANCO MERIDIONAL DO BRASIL']);
        Banco::create(['ban_codigo' => '020', 'ban_nome' => '020 - BANCO DO ESTADO DE ALAGOAS S.A']);
        Banco::create(['ban_codigo' => '021', 'ban_nome' => '021 - BANCO DO ESTADO DO ESPIRITO SANTO S.A']);
        Banco::create(['ban_codigo' => '022', 'ban_nome' => '022 - BANCO DE CREDITO REAL DE MINAS GERAIS SA']);
        Banco::create(['ban_codigo' => '024', 'ban_nome' => '024 - BANCO DO ESTADO DE PERNAMBUCO']);
        Banco::create(['ban_codigo' => '025', 'ban_nome' => '025 - BANCO ALFA S/A']);
        Banco::create(['ban_codigo' => '026', 'ban_nome' => '026 - BANCO DO ESTADO DO ACRE S.A']);
        Banco::create(['ban_codigo' => '027', 'ban_nome' => '027 - BANCO DO ESTADO DE SANTA CATARINA S.A']);
        Banco::create(['ban_codigo' => '028', 'ban_nome' => '028 - BANCO DO ESTADO DA BAHIA S.A']);
        Banco::create(['ban_codigo' => '029', 'ban_nome' => '029 - BANCO DO ESTADO DO RIO DE JANEIRO S.A']);
        Banco::create(['ban_codigo' => '030', 'ban_nome' => '030 - BANCO DO ESTADO DA PARAIBA S.A']);
        Banco::create(['ban_codigo' => '031', 'ban_nome' => '031 - BANCO DO ESTADO DE GOIAS S.A']);
        Banco::create(['ban_codigo' => '032', 'ban_nome' => '032 - BANCO DO ESTADO DO MATO GROSSO S.A.']);
        Banco::create(['ban_codigo' => '033', 'ban_nome' => '033 - BANCO DO ESTADO DE SAO PAULO S.A']);
        Banco::create(['ban_codigo' => '034', 'ban_nome' => '034 - BANCO DO ESADO DO AMAZONAS S.A']);
        Banco::create(['ban_codigo' => '035', 'ban_nome' => '035 - BANCO DO ESTADO DO CEARA S.A']);
        Banco::create(['ban_codigo' => '036', 'ban_nome' => '036 - BANCO DO ESTADO DO MARANHAO S.A']);
        Banco::create(['ban_codigo' => '037', 'ban_nome' => '037 - BANCO DO ESTADO DO PARA S.A]']);
        Banco::create(['ban_codigo' => '038', 'ban_nome' => '038 - BANCO DO ESTADO DO PARANA S.A']);
        Banco::create(['ban_codigo' => '039', 'ban_nome' => '039 - BANCO DO ESTADO DO PIAUI S.A]']);
        Banco::create(['ban_codigo' => '041', 'ban_nome' => '041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A']);
        Banco::create(['ban_codigo' => '047', 'ban_nome' => '047 - BANCO DO ESTADO DE SERGIPE S.A']);
        Banco::create(['ban_codigo' => '048', 'ban_nome' => '048 - BANCO DO ESTADO DE MINAS GERAIS S.A']);
        Banco::create(['ban_codigo' => '059', 'ban_nome' => '059 - BANCO DO ESTADO DE RONDONIA S.A']);
        Banco::create(['ban_codigo' => '070', 'ban_nome' => '070 - BANCO DE BRASILIA S.A]']);
        Banco::create(['ban_codigo' => '104', 'ban_nome' => '104 - CAIXA ECONOMICA FEDERAL']);
        Banco::create(['ban_codigo' => '106', 'ban_nome' => '106 - BANCO ITABANCO S.A.']);
        Banco::create(['ban_codigo' => '107', 'ban_nome' => '107 - BANCO BBM S.A']);
        Banco::create(['ban_codigo' => '109', 'ban_nome' => '109 - BANCO CREDIBANCO S.A']);
        Banco::create(['ban_codigo' => '116', 'ban_nome' => '116 - BANCO B.N.L DO BRASIL S.A']);
        Banco::create(['ban_codigo' => '148', 'ban_nome' => '148 - MULTI BANCO S.A']);
        Banco::create(['ban_codigo' => '151', 'ban_nome' => '151 - CAIXA ECONOMICA DO ESTADO DE SAO PAULO']);
        Banco::create(['ban_codigo' => '153', 'ban_nome' => '153 - CAIXA ECONOMICA DO ESTADO DO R.G.SUL']);
        Banco::create(['ban_codigo' => '165', 'ban_nome' => '165 - BANCO NORCHEM S.A']);
        Banco::create(['ban_codigo' => '166', 'ban_nome' => '166 - BANCO INTER-ATLANTICO S.A']);
        Banco::create(['ban_codigo' => '168', 'ban_nome' => '168 - BANCO C.C.F. BRASIL S.A']);
        Banco::create(['ban_codigo' => '175', 'ban_nome' => '175 - CONTINENTAL BANCO S.A']);
        Banco::create(['ban_codigo' => '184', 'ban_nome' => '184 - BBA - CREDITANSTALT S.A']);
        Banco::create(['ban_codigo' => '199', 'ban_nome' => '199 - BANCO FINANCIAL PORTUGUES']);
        Banco::create(['ban_codigo' => '200', 'ban_nome' => '200 - BANCO FRICRISA AXELRUD S.A']);
        Banco::create(['ban_codigo' => '201', 'ban_nome' => '201 - BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A']);
        Banco::create(['ban_codigo' => '204', 'ban_nome' => '204 - BANCO S.R.L S.A']);
        Banco::create(['ban_codigo' => '205', 'ban_nome' => '205 - BANCO SUL AMERICA S.A']);
        Banco::create(['ban_codigo' => '206', 'ban_nome' => '206 - BANCO MARTINELLI S.A']);
        Banco::create(['ban_codigo' => '208', 'ban_nome' => '208 - BANCO PACTUAL S.A']);
        Banco::create(['ban_codigo' => '210', 'ban_nome' => '210 - DEUTSCH SUDAMERIKANICHE BANK AG']);
        Banco::create(['ban_codigo' => '211', 'ban_nome' => '211 - BANCO SISTEMA S.A']);
        Banco::create(['ban_codigo' => '212', 'ban_nome' => '212 - BANCO MATONE S.A']);
        Banco::create(['ban_codigo' => '213', 'ban_nome' => '213 - BANCO ARBI S.A']);
        Banco::create(['ban_codigo' => '214', 'ban_nome' => '214 - BANCO DIBENS S.A']);
        Banco::create(['ban_codigo' => '215', 'ban_nome' => '215 - BANCO AMERICA DO SUL S.A']);
        Banco::create(['ban_codigo' => '216', 'ban_nome' => '216 - BANCO REGIONAL MALCON S.A']);
        Banco::create(['ban_codigo' => '217', 'ban_nome' => '217 - BANCO AGROINVEST S.A']);
        Banco::create(['ban_codigo' => '218', 'ban_nome' => '218 - BBS - BANCO BONSUCESSO S.A.']);
        Banco::create(['ban_codigo' => '219', 'ban_nome' => '219 - BANCO DE CREDITO DE SAO PAULO S.A']);
        Banco::create(['ban_codigo' => '220', 'ban_nome' => '220 - BANCO CREFISUL']);
        Banco::create(['ban_codigo' => '221', 'ban_nome' => '221 - BANCO GRAPHUS S.A']);
        Banco::create(['ban_codigo' => '222', 'ban_nome' => '222 - BANCO AGF BRASIL S. A.']);
        Banco::create(['ban_codigo' => '223', 'ban_nome' => '223 - BANCO INTERUNION S.A']);
        Banco::create(['ban_codigo' => '224', 'ban_nome' => '224 - BANCO FIBRA S.A']);
        Banco::create(['ban_codigo' => '225', 'ban_nome' => '225 - BANCO BRASCAN S.A']);
        Banco::create(['ban_codigo' => '228', 'ban_nome' => '228 - BANCO ICATU S.A']);
        Banco::create(['ban_codigo' => '229', 'ban_nome' => '229 - BANCO CRUZEIRO S.A']);
        Banco::create(['ban_codigo' => '230', 'ban_nome' => '230 - BANCO BANDEIRANTES S.A']);
        Banco::create(['ban_codigo' => '231', 'ban_nome' => '231 - BANCO BOAVISTA S.A']);
        Banco::create(['ban_codigo' => '232', 'ban_nome' => '232 - BANCO INTERPART S.A']);
        Banco::create(['ban_codigo' => '233', 'ban_nome' => '233 - BANCO MAPPIN S.A']);
        Banco::create(['ban_codigo' => '234', 'ban_nome' => '234 - BANCO LAVRA S.A.']);
        Banco::create(['ban_codigo' => '235', 'ban_nome' => '235 - BANCO LIBERAL S.A']);
        Banco::create(['ban_codigo' => '236', 'ban_nome' => '236 - BANCO CAMBIAL S.A']);
        Banco::create(['ban_codigo' => '237', 'ban_nome' => '237 - BANCO BRADESCO S.A']);
        Banco::create(['ban_codigo' => '239', 'ban_nome' => '239 - BANCO BANCRED S.A']);
        Banco::create(['ban_codigo' => '240', 'ban_nome' => '240 - BANCO DE CREDITO REAL DE MINAS GERAIS S.']);
        Banco::create(['ban_codigo' => '241', 'ban_nome' => '241 - BANCO CLASSICO S.A']);
        Banco::create(['ban_codigo' => '242', 'ban_nome' => '242 - BANCO EUROINVEST S.A']);
        Banco::create(['ban_codigo' => '243', 'ban_nome' => '243 - BANCO STOCK S.A']);
        Banco::create(['ban_codigo' => '244', 'ban_nome' => '244 - BANCO CIDADE S.A']);
        Banco::create(['ban_codigo' => '245', 'ban_nome' => '245 - BANCO EMPRESARIAL S.A']);
        Banco::create(['ban_codigo' => '246', 'ban_nome' => '246 - BANCO ABC ROMA S.A']);
        Banco::create(['ban_codigo' => '247', 'ban_nome' => '247 - BANCO OMEGA S.A']);
        Banco::create(['ban_codigo' => '249', 'ban_nome' => '249 - BANCO INVESTCRED S.A']);
        Banco::create(['ban_codigo' => '250', 'ban_nome' => '250 - BANCO SCHAHIN CURY S.A']);
        Banco::create(['ban_codigo' => '251', 'ban_nome' => '251 - BANCO SAO JORGE S.A.']);
        Banco::create(['ban_codigo' => '252', 'ban_nome' => '252 - BANCO FININVEST S.A']);
        Banco::create(['ban_codigo' => '254', 'ban_nome' => '254 - BANCO PARANA BANCO S.A']);
        Banco::create(['ban_codigo' => '255', 'ban_nome' => '255 - MILBANCO S.A.']);
        Banco::create(['ban_codigo' => '256', 'ban_nome' => '256 - BANCO GULVINVEST S.A']);
        Banco::create(['ban_codigo' => '258', 'ban_nome' => '258 - BANCO INDUSCRED S.A']);
        Banco::create(['ban_codigo' => '261', 'ban_nome' => '261 - BANCO VARIG S.A']);
        Banco::create(['ban_codigo' => '262', 'ban_nome' => '262 - BANCO BOREAL S.A']);
        Banco::create(['ban_codigo' => '263', 'ban_nome' => '263 - BANCO CACIQUE']);
        Banco::create(['ban_codigo' => '264', 'ban_nome' => '264 - BANCO PERFORMANCE S.A']);
        Banco::create(['ban_codigo' => '265', 'ban_nome' => '265 - BANCO FATOR S.A']);
        Banco::create(['ban_codigo' => '266', 'ban_nome' => '266 - BANCO CEDULA S.A']);
        Banco::create(['ban_codigo' => '267', 'ban_nome' => '267 - BANCO BBM-COM.C.IMOB.CFI S.A.']);
        Banco::create(['ban_codigo' => '275', 'ban_nome' => '275 - BANCO REAL S.A']);
        Banco::create(['ban_codigo' => '277', 'ban_nome' => '277 - BANCO PLANIBANC S.A']);
        Banco::create(['ban_codigo' => '282', 'ban_nome' => '282 - BANCO BRASILEIRO COMERCIAL']);
        Banco::create(['ban_codigo' => '291', 'ban_nome' => '291 - BANCO DE CREDITO NACIONAL S.A']);
        Banco::create(['ban_codigo' => '294', 'ban_nome' => '294 - BCR - BANCO DE CREDITO REAL S.A']);
        Banco::create(['ban_codigo' => '295', 'ban_nome' => '295 - BANCO CREDIPLAN S.A']);
        Banco::create(['ban_codigo' => '300', 'ban_nome' => '300 - BANCO DE LA NACION ARGENTINA S.A']);
        Banco::create(['ban_codigo' => '302', 'ban_nome' => '302 - BANCO DO PROGRESSO S.A']);
        Banco::create(['ban_codigo' => '303', 'ban_nome' => '303 - BANCO HNF S.A.']);
        Banco::create(['ban_codigo' => '304', 'ban_nome' => '304 - BANCO PONTUAL S.A']);
        Banco::create(['ban_codigo' => '308', 'ban_nome' => '308 - BANCO COMERCIAL BANCESA S.A.']);
        Banco::create(['ban_codigo' => '318', 'ban_nome' => '318 - BANCO B.M.G. S.A']);
        Banco::create(['ban_codigo' => '320', 'ban_nome' => '320 - BANCO INDUSTRIAL E COMERCIAL']);
        Banco::create(['ban_codigo' => '341', 'ban_nome' => '341 - BANCO ITAU S.A']);
        Banco::create(['ban_codigo' => '346', 'ban_nome' => '346 - BANCO FRANCES E BRASILEIRO S.A']);
        Banco::create(['ban_codigo' => '347', 'ban_nome' => '347 - BANCO SUDAMERIS BRASIL S.A']);
        Banco::create(['ban_codigo' => '351', 'ban_nome' => '351 - BANCO BOZANO SIMONSEN S.A']);
        Banco::create(['ban_codigo' => '353', 'ban_nome' => '353 - BANCO GERAL DO COMERCIO S.A']);
        Banco::create(['ban_codigo' => '356', 'ban_nome' => '356 - ABN AMRO S.A']);
        Banco::create(['ban_codigo' => '366', 'ban_nome' => '366 - BANCO SOGERAL S.A']);
        Banco::create(['ban_codigo' => '369', 'ban_nome' => '369 - PONTUAL']);
        Banco::create(['ban_codigo' => '370', 'ban_nome' => '370 - BEAL - BANCO EUROPEU PARA AMERICA LATINA']);
        Banco::create(['ban_codigo' => '372', 'ban_nome' => '372 - BANCO ITAMARATI S.A']);
        Banco::create(['ban_codigo' => '375', 'ban_nome' => '375 - BANCO FENICIA S.A']);
        Banco::create(['ban_codigo' => '376', 'ban_nome' => '376 - CHASE MANHATTAN BANK S.A']);
        Banco::create(['ban_codigo' => '388', 'ban_nome' => '388 - BANCO MERCANTIL DE DESCONTOS S/A']);
        Banco::create(['ban_codigo' => '389', 'ban_nome' => '389 - BANCO MERCANTIL DO BRASIL S.A']);
        Banco::create(['ban_codigo' => '392', 'ban_nome' => '392 - BANCO MERCANTIL DE SAO PAULO S.A']);
        Banco::create(['ban_codigo' => '394', 'ban_nome' => '394 - BANCO B.M.C. S.A']);
        Banco::create(['ban_codigo' => '399', 'ban_nome' => '399 - BANCO BAMERINDUS DO BRASIL S.A']);
        Banco::create(['ban_codigo' => '409', 'ban_nome' => '409 - UNIBANCO - UNIAO DOS BANCOS BRASILEIROS']);
        Banco::create(['ban_codigo' => '412', 'ban_nome' => '412 - BANCO NACIONAL DA BAHIA S.A']);
        Banco::create(['ban_codigo' => '415', 'ban_nome' => '415 - BANCO NACIONAL S.A']);
        Banco::create(['ban_codigo' => '420', 'ban_nome' => '420 - BANCO NACIONAL DO NORTE S.A']);
        Banco::create(['ban_codigo' => '422', 'ban_nome' => '422 - BANCO SAFRA S.A']);
        Banco::create(['ban_codigo' => '424', 'ban_nome' => '424 - BANCO NOROESTE S.A']);
        Banco::create(['ban_codigo' => '434', 'ban_nome' => '434 - BANCO FORTALEZA S.A']);
        Banco::create(['ban_codigo' => '453', 'ban_nome' => '453 - BANCO RURAL S.A']);
        Banco::create(['ban_codigo' => '456', 'ban_nome' => '456 - BANCO TOKIO S.A']);
        Banco::create(['ban_codigo' => '464', 'ban_nome' => '464 - BANCO SUMITOMO BRASILEIRO S.A']);
        Banco::create(['ban_codigo' => '466', 'ban_nome' => '466 - BANCO MITSUBISHI BRASILEIRO S.A']);
        Banco::create(['ban_codigo' => '472', 'ban_nome' => '472 - LLOYDS BANK PLC']);
        Banco::create(['ban_codigo' => '473', 'ban_nome' => '473 - BANCO FINANCIAL PORTUGUES S.A']);
        Banco::create(['ban_codigo' => '477', 'ban_nome' => '477 - CITIBANK N.A']);
        Banco::create(['ban_codigo' => '479', 'ban_nome' => '479 - BANCO DE BOSTON S.A']);
        Banco::create(['ban_codigo' => '480', 'ban_nome' => '480 - BANCO PORTUGUES DO ATLANTICO-BRASIL S.A']);
        Banco::create(['ban_codigo' => '483', 'ban_nome' => '483 - BANCO AGRIMISA S.A.']);
        Banco::create(['ban_codigo' => '487', 'ban_nome' => '487 - DEUTSCHE BANK S.A - BANCO ALEMAO']);
        Banco::create(['ban_codigo' => '488', 'ban_nome' => '488 - BANCO J. P. MORGAN S.A']);
        Banco::create(['ban_codigo' => '489', 'ban_nome' => '489 - BANESTO BANCO URUGAUAY S.A']);
        Banco::create(['ban_codigo' => '492', 'ban_nome' => '492 - INTERNATIONALE NEDERLANDEN BANK N.V.']);
        Banco::create(['ban_codigo' => '493', 'ban_nome' => '493 - BANCO UNION S.A.C.A']);
        Banco::create(['ban_codigo' => '494', 'ban_nome' => '494 - BANCO LA REP. ORIENTAL DEL URUGUAY']);
        Banco::create(['ban_codigo' => '495', 'ban_nome' => '495 - BANCO LA PROVINCIA DE BUENOS AIRES']);
        Banco::create(['ban_codigo' => '496', 'ban_nome' => '496 - BANCO EXTERIOR DE ESPANA S.A']);
        Banco::create(['ban_codigo' => '498', 'ban_nome' => '498 - CENTRO HISPANO BANCO']);
        Banco::create(['ban_codigo' => '499', 'ban_nome' => '499 - BANCO IOCHPE S.A']);
        Banco::create(['ban_codigo' => '501', 'ban_nome' => '501 - BANCO BRASILEIRO IRAQUIANO S.A.']);
        Banco::create(['ban_codigo' => '502', 'ban_nome' => '502 - BANCO SANTANDER S.A']);
        Banco::create(['ban_codigo' => '504', 'ban_nome' => '504 - BANCO MULTIPLIC S.A']);
        Banco::create(['ban_codigo' => '505', 'ban_nome' => '505 - BANCO GARANTIA S.A']);
        Banco::create(['ban_codigo' => '600', 'ban_nome' => '600 - BANCO LUSO BRASILEIRO S.A']);
        Banco::create(['ban_codigo' => '601', 'ban_nome' => '601 - BFC BANCO S.A.']);
        Banco::create(['ban_codigo' => '602', 'ban_nome' => '602 - BANCO PATENTE S.A']);
        Banco::create(['ban_codigo' => '604', 'ban_nome' => '604 - BANCO INDUSTRIAL DO BRASIL S.A']);
        Banco::create(['ban_codigo' => '607', 'ban_nome' => '607 - BANCO SANTOS NEVES S.A']);
        Banco::create(['ban_codigo' => '608', 'ban_nome' => '608 - BANCO OPEN S.A']);
        Banco::create(['ban_codigo' => '610', 'ban_nome' => '610 - BANCO V.R. S.A']);
        Banco::create(['ban_codigo' => '611', 'ban_nome' => '611 - BANCO PAULISTA S.A']);
        Banco::create(['ban_codigo' => '612', 'ban_nome' => '612 - BANCO GUANABARA S.A']);
        Banco::create(['ban_codigo' => '613', 'ban_nome' => '613 - BANCO PECUNIA S.A']);
        Banco::create(['ban_codigo' => '616', 'ban_nome' => '616 - BANCO INTERPACIFICO S.A']);
        Banco::create(['ban_codigo' => '617', 'ban_nome' => '617 - BANCO INVESTOR S.A.']);
        Banco::create(['ban_codigo' => '618', 'ban_nome' => '618 - BANCO TENDENCIA S.A']);
        Banco::create(['ban_codigo' => '621', 'ban_nome' => '621 - BANCO APLICAP S.A.']);
        Banco::create(['ban_codigo' => '622', 'ban_nome' => '622 - BANCO DRACMA S.A']);
        Banco::create(['ban_codigo' => '623', 'ban_nome' => '623 - BANCO PANAMERICANO S.A']);
        Banco::create(['ban_codigo' => '624', 'ban_nome' => '624 - BANCO GENERAL MOTORS S.A']);
        Banco::create(['ban_codigo' => '625', 'ban_nome' => '625 - BANCO ARAUCARIA S.A']);
        Banco::create(['ban_codigo' => '626', 'ban_nome' => '626 - BANCO FICSA S.A']);
        Banco::create(['ban_codigo' => '627', 'ban_nome' => '627 - BANCO DESTAK S.A']);
        Banco::create(['ban_codigo' => '628', 'ban_nome' => '628 - BANCO CRITERIUM S.A']);
        Banco::create(['ban_codigo' => '629', 'ban_nome' => '629 - BANCORP BANCO COML. E. DE INVESTMENTO']);
        Banco::create(['ban_codigo' => '630', 'ban_nome' => '630 - BANCO INTERCAP S.A']);
        Banco::create(['ban_codigo' => '633', 'ban_nome' => '633 - BANCO REDIMENTO S.A']);
        Banco::create(['ban_codigo' => '634', 'ban_nome' => '634 - BANCO TRIANGULO S.A']);
        Banco::create(['ban_codigo' => '635', 'ban_nome' => '635 - BANCO DO ESTADO DO AMAPA S.A']);
        Banco::create(['ban_codigo' => '637', 'ban_nome' => '637 - BANCO SOFISA S.A']);
        Banco::create(['ban_codigo' => '638', 'ban_nome' => '638 - BANCO PROSPER S.A']);
        Banco::create(['ban_codigo' => '639', 'ban_nome' => '639 - BIG S.A. - BANCO IRMAOS GUIMARAES']);
        Banco::create(['ban_codigo' => '640', 'ban_nome' => '640 - BANCO DE CREDITO METROPOLITANO S.A']);
        Banco::create(['ban_codigo' => '641', 'ban_nome' => '641 - BANCO EXCEL ECONOMICO S/A']);
        Banco::create(['ban_codigo' => '643', 'ban_nome' => '643 - BANCO SEGMENTO S.A']);
        Banco::create(['ban_codigo' => '645', 'ban_nome' => '645 - BANCO DO ESTADO DE RORAIMA S.A']);
        Banco::create(['ban_codigo' => '647', 'ban_nome' => '647 - BANCO MARKA S.A']);
        Banco::create(['ban_codigo' => '648', 'ban_nome' => '648 - BANCO ATLANTIS S.A']);
        Banco::create(['ban_codigo' => '649', 'ban_nome' => '649 - BANCO DIMENSAO S.A']);
        Banco::create(['ban_codigo' => '650', 'ban_nome' => '650 - BANCO PEBB S.A']);
        Banco::create(['ban_codigo' => '652', 'ban_nome' => '652 - BANCO FRANCES E BRASILEIRO SA']);
        Banco::create(['ban_codigo' => '653', 'ban_nome' => '653 - BANCO INDUSVAL S.A']);
        Banco::create(['ban_codigo' => '654', 'ban_nome' => '654 - BANCO A. J. RENNER S.A']);
        Banco::create(['ban_codigo' => '655', 'ban_nome' => '655 - BANCO VOTORANTIM S.A.']);
        Banco::create(['ban_codigo' => '656', 'ban_nome' => '656 - BANCO MATRIX S.A']);
        Banco::create(['ban_codigo' => '657', 'ban_nome' => '657 - BANCO TECNICORP S.A']);
        Banco::create(['ban_codigo' => '658', 'ban_nome' => '658 - BANCO PORTO REAL S.A']);
        Banco::create(['ban_codigo' => '702', 'ban_nome' => '702 - BANCO SANTOS S.A']);
        Banco::create(['ban_codigo' => '705', 'ban_nome' => '705 - BANCO INVESTCORP S.A.']);
        Banco::create(['ban_codigo' => '707', 'ban_nome' => '707 - BANCO DAYCOVAL S.A']);
        Banco::create(['ban_codigo' => '711', 'ban_nome' => '711 - BANCO VETOR S.A.']);
        Banco::create(['ban_codigo' => '713', 'ban_nome' => '713 - BANCO CINDAM S.A']);
        Banco::create(['ban_codigo' => '715', 'ban_nome' => '715 - BANCO VEGA S.A']);
        Banco::create(['ban_codigo' => '718', 'ban_nome' => '718 - BANCO OPERADOR S.A']);
        Banco::create(['ban_codigo' => '719', 'ban_nome' => '719 - BANCO PRIMUS S.A']);
        Banco::create(['ban_codigo' => '720', 'ban_nome' => '720 - BANCO MAXINVEST S.A']);
        Banco::create(['ban_codigo' => '721', 'ban_nome' => '721 - BANCO CREDIBEL S.A']);
        Banco::create(['ban_codigo' => '722', 'ban_nome' => '722 - BANCO INTERIOR DE SAO PAULO S.A']);
        Banco::create(['ban_codigo' => '724', 'ban_nome' => '724 - BANCO PORTO SEGURO S.A']);
        Banco::create(['ban_codigo' => '725', 'ban_nome' => '725 - BANCO FINABANCO S.A']);
        Banco::create(['ban_codigo' => '726', 'ban_nome' => '726 - BANCO UNIVERSAL S.A']);
        Banco::create(['ban_codigo' => '728', 'ban_nome' => '728 - BANCO FITAL S.A']);
        Banco::create(['ban_codigo' => '729', 'ban_nome' => '729 - BANCO FONTE S.A']);
        Banco::create(['ban_codigo' => '730', 'ban_nome' => '730 - BANCO COMERCIAL PARAGUAYO S.A']);
        Banco::create(['ban_codigo' => '731', 'ban_nome' => '731 - BANCO GNPP S.A.']);
        Banco::create(['ban_codigo' => '732', 'ban_nome' => '732 - BANCO PREMIER S.A.']);
        Banco::create(['ban_codigo' => '733', 'ban_nome' => '733 - BANCO NACOES S.A.']);
        Banco::create(['ban_codigo' => '734', 'ban_nome' => '734 - BANCO GERDAU S.A']);
        Banco::create(['ban_codigo' => '735', 'ban_nome' => '735 - BACO POTENCIAL']);
        Banco::create(['ban_codigo' => '736', 'ban_nome' => '736 - BANCO UNITED S.A']);
        Banco::create(['ban_codigo' => '737', 'ban_nome' => '737 - THECA']);
        Banco::create(['ban_codigo' => '738', 'ban_nome' => '738 - MARADA']);
        Banco::create(['ban_codigo' => '739', 'ban_nome' => '739 - BGN']);
        Banco::create(['ban_codigo' => '740', 'ban_nome' => '740 - BCN BARCLAYS']);
        Banco::create(['ban_codigo' => '741', 'ban_nome' => '741 - BRP']);
        Banco::create(['ban_codigo' => '742', 'ban_nome' => '742 - EQUATORIAL']);
        Banco::create(['ban_codigo' => '743', 'ban_nome' => '743 - BANCO EMBLEMA S.A']);
        Banco::create(['ban_codigo' => '744', 'ban_nome' => '744 - THE FIRST NATIONAL BANK OF BOSTON']);
        Banco::create(['ban_codigo' => '745', 'ban_nome' => '745 - CITIBAN N.A.']);
        Banco::create(['ban_codigo' => '746', 'ban_nome' => '746 - MODAL S\A']);
        Banco::create(['ban_codigo' => '747', 'ban_nome' => '747 - RAIBOBANK DO BRASIL']);
        Banco::create(['ban_codigo' => '748', 'ban_nome' => '748 - SICREDI']);
        Banco::create(['ban_codigo' => '749', 'ban_nome' => '749 - BRMSANTIL SA']);
        Banco::create(['ban_codigo' => '750', 'ban_nome' => '750 - BANCO REPUBLIC NATIONAL OF NEW YORK (BRA']);
        Banco::create(['ban_codigo' => '751', 'ban_nome' => '751 - DRESDNER BANK LATEINAMERIKA-BRASIL S/A']);
        Banco::create(['ban_codigo' => '752', 'ban_nome' => '752 - BANCO BANQUE NATIONALE DE PARIS BRASIL S']);
        Banco::create(['ban_codigo' => '753', 'ban_nome' => '753 - BANCO COMERCIAL URUGUAI S.A.']);
        Banco::create(['ban_codigo' => '755', 'ban_nome' => '755 - BANCO MERRILL LYNCH S.A']);
        Banco::create(['ban_codigo' => '756', 'ban_nome' => '756 - BANCO COOPERATIVO DO BRASIL S.A.']);
        Banco::create(['ban_codigo' => '757', 'ban_nome' => '757 - BANCO KEB DO BRASIL S.A.']);
    }
}
